version: '3'
services:
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8082:8082"
    build:
      context: ./
      dockerfile: DockerFile
#
#
#money-rest-api:
#  image: money-rest-api
#  network_mode: bridge
#  container_name: money-rest-api
#  build:
#    context: ./
#    dockerfile: Dockerfile
#  ports:
#    - 8080:8080